### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/openCypher/commit/e0d702c57fae705831846cb17b3c1e9878dbd861#commitcomment-47775450

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/openCypher/commit/00bc2f5b4900c86f9a784080ff1a342eee78db3c

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### CODE REVIEW

**Comment by thobe** [comment]
Thank you for this @jsoref.

In order for me to be able to merge this change, could you please sign the openCypher Contributors Agreement?
Please see https://www.opencypher.org/occa for instructions.

**Comment by jsoref** [comment]
@thobe: submitted

**Comment by thobe** [comment]
Thank you!

**Comment by jsoref** [comment]
If you'd like the action to help the project going forward, let me know.

**Pull request merged**
