### PR TITLE
Missing node variable in test

### PR DESCRIPTION
**Pull request by AviAvni**

### CODE REVIEW

**Comment by Mats-SX** [comment]
@AviAvni Thanks for the contribution. In order to merge your change, we need you to sign the openCypher Contributors Agreement (oCCA) as per the instructions here: https://github.com/opencypher/openCypher/blob/master/CONTRIBUTING.adoc

**Comment by Mats-SX** [comment]
@hvub This error would've been caught by running the TCK against a backend (like Neo4j). Perhaps it would be a good idea to incorporate that in the process of categorising the TCK (if you haven't already)?

**Comment by AviAvni** [comment]
I can't sign the oCCA for now sorry
so for one character you can do the change so i'm closing it

**Comment by Mats-SX** [comment]
@AviAvni I understand. Thank you for turning our attention to this issue!

**Comment by hvub** [comment]
Cardified.

**Pull request closed without merging**
