### PR TITLE
Added CIP2018-10-29 EXISTS and IS NOT NULL

### PR DESCRIPTION
**Pull request by sherfert**
[CIP](https://github.com/sherfert/openCypher/blob/CIP-exists-is-not-null/cip/1.accepted/CIP2018-10-29-EXISTS-and-IS-NOT-NULL.adoc)

### CODE REVIEW

**Comment by boggle** [comment]
Please always add a link to the description to the rendered version! That helps people to review CIPs

**Comment by boggle** [comment]
Otherwise great CIP, I'm torn on the constraints change. Probably good to keep as is here but we need to look at those more holistically in a different CIP. A good next step might be to have a discussion about having a shrothand notation for `IS NOT NULL` and wether we want to add this here.

**Comment by Mats-SX** [comment]
@sherfert I would like this CIP to also rewrite the section in the CIP it refers to changing. At the very least, insert a forward-reference pointing to this CIP. This is in order to not confuse readers of the older CIP.

**Comment by thobe** [comment]
Accepted by lazy consensus: https://groups.google.com/forum/#!topic/opencypher/cAccRlkHdp8

**Pull request merged**
